name: flutter_accessibility
description: "Flutter Package containing utility widgets to help with Semantics in Flutter apps"
version: 0.0.3
publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub/
homepage: https://github.com/Iconica-Development/flutter_accessibility
repository: https://github.com/Iconica-Development/flutter_accessibility

environment:
  sdk: ^3.5.3
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^7.0.0
